---
Name: elemental-extension
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - tbone/elemental-extension:client/dist/js/main.bundle.js
  extra_requirements_css:
    - tbone/elemental-extension:client/dist/styles/main.css